name: "Deploy API"

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_AWS_RDS_ENDPOINT: ${{ secrets.AWS_RDS_ENDPOINT }}
      TF_VAR_DB_USERNAME: ${{ secrets.DB_USERNAME }}
      TF_VAR_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      TF_VAR_DB_PORT: ${{ secrets.DB_PORT }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup JDK
        id: setup-jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Package Jar
        run: mvn -B package --file pom.xml -DskipTests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GITHUB_ACTION_EBS
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Validate Identity with AWS
        working-directory: ./infrastructure
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        id: init
        working-directory: ./infrastructure
        run: terraform init

      - name: Generate infrastructure plan
        id: plan
        working-directory: ./infrastructure
        run: terraform plan -out=.tfplan

      - name: Apply infrastructure plan
        id: apply
        working-directory: ./infrastructure
        run: terraform apply .tfplan